apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nailsapps.nails-cli.dev
  namespace: default # For easier deployment and avoid permissions collisions on most clusters, the resource is namespace-scoped. More information at: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
spec:
  group: nails-cli.dev
  names:
    kind: NailsApp
    plural: nailsapps
    singular: nailsapp
    shortNames:
      - nailsapp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hostname-url:
                  type: string
                web:
                  type: object
                  properties:
                    image:
                      type: string
                  required:
                    - image
              required:
              - hostname-url
              - web
