apiVersion: v1
kind: ServiceAccount
metadata:
  name: stack-operator-service-account
  namespace: stack

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stack-operator-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stack-operator-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: stack-operator-service-account
  namespace: stack
roleRef:
  kind: ClusterRole
  name: stack-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stack-operator-deployment
  namespace: stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stack-operator
  template:
    metadata:
      labels:
        app: stack-operator
    spec:
      serviceAccountName: stack-operator-service-account
      containers:
      - name: stack-operator
        image: purtontech/stack-operator:1.3.31
