apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stackapps.stack-cli.dev
  namespace: default # For easier deployment and avoid permissions collisions on most clusters, the resource is namespace-scoped. More information at: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
spec:
  group: stack-cli.dev
  names:
    kind: StackApp
    plural: stackapps
    singular: stackapp
    shortNames:
      - stackapp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                web:
                  type: object
                  properties:
                    image:
                      type: string
                    port:
                      type: integer
                      format: int32
                  required:
                    - image
                    - port
                auth:
                  type: object
                  properties:
                    hostname-url:
                      type: string
                    jwt:
                      type: string
              required:
              - web
