# The URL the site will be built for
base_url = "https://rust-on-nails.com"
title = "Rust on Nails"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "tech-startup-theme"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

highlight_themes_css = [
  { theme = "kronuz", filename = "syntax-theme.css" },
]

[extra]
# Put all your custom variables here
#ga_analytics = "G-NSK5LPX8EN"

goat_counter = "https://cloak.goatcounter.com/count"

first_doc_page = "/docs/ide-setup/introduction/"

copyright = "Copyright 2021 - 2023"

# Every page CTA. At the bottom of every blog post we have a cta
every_page_cta = { title = "It takes 30 seconds to sign up for our free plan", cta_button = "Sign Up" }

# On the footer we have a signup button and a call to action, set the text here
footer_cta = { title = "Sign Up for Free", prompt = "Take control of your application config and secrets", cta_button = "Check it Out" }

# Where shall we point the sign in and sign up buttons.
authentication = { sign_up = "https://app.cloak.software/auth/sign_up", sign_in = "https://app.cloak.software/auth/sign_in" }
# When running on localhost you can set the sign up and sign links to somewhere else.
localhost = "http://localhost:7104"
authentication_development = { sign_up = "/auth/sign_up", sign_in = "/auth/sign_in" }

# Information required by terms and privacy pages.
support_email = "support@cloak.software"
company_address = "71-75 Shelton Street, London, LND, WC2H 9JQ, United Kingdom"

# Social icons (shown on the footer)
github_repo = "https://github.com/purton-tech/cloak"

# Resources on the footer (LHS)
resources_1 = [
    {name = "Blog", url = "/blog"},
    {name = "Documentation", url = "/documentation"},
    {name = "FAQ", url = "/blog"},
]

resources_2 = [
    {name = "Pricing", url = "/pricing"},
    {name = "Mission", url = "/blog"},
    {name = "Careers", url = "/blog"},
]

menu_items = [
]

# Documentation sections
doc_sections = [
    {name = "Reference", location = "reference"},
]

# Blog tile and subtitle
blog_title = "The Cloak Blog"
blog_subtitle = "Defence in Depth For Full Stack Web Applications"
